импортируем модуль NumPy

In [5]:
import numpy as np

создадим массивы класса ndarray из обычных списков и продемонстрируем работу основных атрибутов shape - возвращает форму массива, dtype - возвращает тип данных, хранящихся в массиве

In [ ]:
massive = np.array([1, 2.1, 4])

In [53]:
massive.shape

(3,)

In [54]:
massive.dtype

dtype('float64')

создадим двумерный, трехмерный массивы

In [55]:
b = np.array([[11, 2.1, 15], [1, 2, 3]])
c = np.array([[11, 2.1, 15], [1, 2, 3], [3,4,5]])

In [56]:
b.shape

(2, 3)

In [57]:
c.shape

(3, 3)

с помощью функций zeros() и ones() можно создать многомерные массивы заполненные нулями и единицами соответственно

In [58]:
zero_massive = np.zeros((3,4))
zero_massive

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
zero_massive.shape

(3, 4)

In [60]:
ones_massive = np.ones((2,5))
ones_massive

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
ones_massive.shape

(2, 5)

создадим массив последовательности чисел с помощью функции arange()

In [62]:
mass_of_nums = np.arange(0,1,0.01)
mass_of_nums

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

Попробуем провести стандартные операции с массивами

In [63]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7])

In [64]:
c = a+b
c

array([ 5,  7,  9, 11])

In [65]:
c = a-b
c

array([-3, -3, -3, -3])

In [66]:
c = a*b
c

array([ 4, 10, 18, 28])

In [67]:
c = a/b
c

array([0.25      , 0.4       , 0.5       , 0.57142857])

In [68]:
c = a%b
c

array([1, 2, 3, 4])

In [69]:
c = a**b
c

array([    1,    32,   729, 16384])

Попробуем поработать со срезами и индексами массива

In [70]:
a = np.arange(15)**5
a

array([     0,      1,     32,    243,   1024,   3125,   7776,  16807,
        32768,  59049, 100000, 161051, 248832, 371293, 537824])

In [71]:
a[3]

np.int64(243)

In [72]:
a[2:5]

array([  32,  243, 1024])

In [73]:
a[2:10:2]

array([   32,  1024,  7776, 32768])

In [74]:
c = a[[3,4]]
c

array([ 243, 1024])

In [75]:
b = np.array([[11, 2.1, 15], 
              [1, 2, 3], 
              [3,4,5]])
b

array([[11. ,  2.1, 15. ],
       [ 1. ,  2. ,  3. ],
       [ 3. ,  4. ,  5. ]])

In [77]:
b[1]

array([1., 2., 3.])

In [79]:
b[[2,2]]

array([[3., 4., 5.],
       [3., 4., 5.]])

In [80]:
b[:,2]

array([15.,  3.,  5.])

воспользуемся функцией mean() чтобы высчитать среднее значение элементов массива

In [6]:
b = np.array([[11, 2.1, 15], 
              [1, 2, 3], 
              [3,4,5]])
b.mean()

np.float64(5.122222222222223)